FROM python:3.12.4-alpine3.20

WORKDIR /app

COPY requirements.txt /app/

RUN apk add --no-cache protobuf-dev

RUN pip install --no-cache-dir -r requirements.txt


COPY . /app


ENTRYPOINT [ "./start.sh" ]

