FROM python:3.12.4-alpine3.20 AS builder

WORKDIR /app

COPY ./bot-player-service/requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

RUN apk add --no-cache protobuf-dev

RUN pip install gunicorn

COPY ./bot-player-service/ .

COPY ./protos ./protos

RUN chmod +x compile-protos.sh && ./compile-protos.sh

ENV FLASK_ENV=production

CMD sh -c "gunicorn --bind 0.0.0.0:8000 server:app"
