FROM node:22.4-alpine3.19 AS builder

WORKDIR /app

COPY ./package*.json ./

RUN npm install

COPY . ./

ENV VITE_API_URL=rudolf-hrytseniak.lol/api

RUN npm run build

FROM node:22.4-alpine3.19 AS release

WORKDIR /app 

COPY --from=builder /app/dist ./dist