# TODO: use shared image for protos
services:
  auth-db:
    image: postgres:16-alpine
    container_name: auth-db-prod
    environment:
      POSTGRES_DB: $POSTGRES_AUTH_DB_NAME
      POSTGRES_USER: $POSTGRES_AUTH_USER_NAME
      POSTGRES_PASSWORD: $POSTGRES_AUTH_USER_PASSWORD
    ports:
      - "5433:5432" 
    volumes:
      - pgdata1:/var/lib/postgresql/data
    networks:
      - auth-network
  auth-service:
    container_name: auth-service-prod
    build:
      context: ./auth-service
      dockerfile: Dockerfile.prod
    ports:
      - "5004:5004"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_USE_RUNNING_IN_CONTAINER=true
      - JWT_SECRET=$JWT_SECRET
      - ENCRYPTION_PASS=$ENCRYPTION_PASS
      - PostgresConnection=Host=auth-db;Database=$POSTGRES_AUTH_DB_NAME;Username=$POSTGRES_AUTH_USER_NAME;Password=$POSTGRES_AUTH_USER_PASSWORD
    depends_on:
      - auth-db
    networks:
      - auth-network
    volumes:
      - ./localhost.crt:/app/localhost.crt
      - ./localhost.key:/app/localhost.key
      - ./private_key.pem:/app/private_key.pem
  
  game-service-db:
    image: postgres:16-alpine
    container_name: game-service-db-prod
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGPORT: 5434
    ports:
      - "5434:5434"
    volumes: 
      - ./game-service/docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - pgdata2:/var/lib/postgresql/data
    networks:
      - backend-network
  game-service:
    container_name: game-service-prod
    build:
      context: .
      dockerfile: ./game-service/Dockerfile.prod
    ports:
      - "7878:7878"
    networks:
      - backend-network
    volumes:
      - ./localhost.crt:/usr/local/bin/app/src/localhost.crt
      - ./localhost.key:/usr/local/bin/app/src/localhost.key
    environment:
      RUN_IN_DOCKER: true
      IP_PORT: 0.0.0.0:7878
      DATABASE_URL: postgres://$POSTGRES_GAME_SERVICE_USER_NAME:$POSTGRES_GAME_SERVICE_USER_PASSWORD@game-service-db:5434/$POSTGRES_GAME_SERVICE_DB_NAME
    depends_on:
      - game-service-db
  game-cordinator-service:
    container_name: game-cordinator-service-prod
    build:
      context: ./game-cordinator-service
      dockerfile: Dockerfile.prod
    ports:
      - "8081:8081"
      - "6380:6379"
    volumes:
      - redis-data:/data
    networks:
      - backend-network
  bot-player-service:
    container_name: bot-player-service-prod
    build:
      context: .
      dockerfile: ./bot-player-service/Dockerfile.prod
    environment:
      - GROQ_API=$GROQ_API
    ports:
      - "5000:5000"
  load-balancer:
    container_name: load-balancer-prod
    build:
      context: ./load-balancer
      dockerfile: Dockerfile.prod
    ports:
      - "8082:8082"
    volumes:
      - ./load-balancer/prod/conf.d:/etc/nginx/conf.d/
      - ./localhost.crt:/usr/local/openresty/certs/localhost.crt
      - ./localhost.key:/usr/local/openresty/certs/localhost.key
      - ./public_key.pem:/etc/nginx/ssl/public_key.pem
      - ./load-balancer/request.lua:/request.lua
    environment:
      - JWT_PUBLIC_KEY_FILE_PATH=/etc/nginx/ssl/public_key.pem
      - REDIS_HOST=game-cordinator-service-prod
      - REDIS_PORT=6379
    depends_on:
      - game-cordinator-service
      - frontend
    networks:
      - backend-network
      - frontend-network
      - auth-network
  frontend:
    container_name: frontend-prod
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    volumes:
      - ./frontend/src:/app/src
    networks:
      - frontend-network
volumes:
  cargo-cache:
  pgdata1:
  pgdata2:
  target-cache:
  redis-data:

networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge
  auth-network:
    driver: bridge