# TODO: use shared image for protos
# Add db migrations image mechanism to update db
services:
  auth-db:
    image: postgres:16-alpine
    container_name: auth-db-prod
    environment:
      POSTGRES_DB: $POSTGRES_AUTH_DB_NAME
      POSTGRES_USER: $POSTGRES_AUTH_USER_NAME
      POSTGRES_PASSWORD: $POSTGRES_AUTH_USER_PASSWORD 
    volumes:
      - pgdata1:/var/lib/postgresql/data
    networks:
      - auth-network
  auth-service:
    image: whattablackhole/fun_poker-auth-service-prod:latest
    container_name: auth-service-prod
    build:
      context: ./auth-service
      dockerfile: Dockerfile.prod
    environment:
      - JWT_SECRET=$JWT_SECRET
      - ENCRYPTION_PASS=$ENCRYPTION_PASS
      - POSTGRES_CONNECTION=Host=auth-db;Database=$POSTGRES_AUTH_DB_NAME;Username=$POSTGRES_AUTH_USER_NAME;Password=$POSTGRES_AUTH_USER_PASSWORD
    depends_on:
      - auth-db
    networks:
      - auth-network
    volumes:
      - ${CERT_PATH}:/app/certs/fullchain.pem
      - ${CERT_KEY_PATH}:/app/certs/privkey.pem
      - ./private_key.pem:/app/private_key.pem
  game-service-db:
    image: postgres:16-alpine
    container_name: game-service-db-prod
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGPORT: 5434
    volumes: 
      # TODO: remove this volume
      - ./game-service/docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - pgdata2:/var/lib/postgresql/data
    networks:
      - backend-network
  game-service:
    container_name: game-service-prod
    image: whattablackhole/fun_poker-game-service-prod:latest
    build:
      context: .
      dockerfile: ./game-service/Dockerfile.prod
    networks:
      - backend-network
    volumes:
      - ${CERT_PATH}:/usr/local/bin/app/src/fullchain.pem
      - ${CERT_KEY_PATH}:/usr/local/bin/app/src/privkey.pem
    environment:
      RUN_IN_DOCKER: true
      CERT_PATH: ./src/fullchain.pem
      CERT_PRIVATE_KEY_PATH: ./src/privkey.pem
      IP_PORT: 0.0.0.0:7878
      DATABASE_URL: postgres://$POSTGRES_GAME_SERVICE_USER_NAME:$POSTGRES_GAME_SERVICE_USER_PASSWORD@game-service-db:5434/$POSTGRES_GAME_SERVICE_DB_NAME
    depends_on:
      - game-service-db
  game-cordinator-service:
    image: whattablackhole/fun_poker-game-cordinator-service-prod:latest
    container_name: game-cordinator-service-prod
    build:
      context: ./game-cordinator-service
      dockerfile: Dockerfile.prod
    volumes:
      - redis-data:/data
    networks:
      - backend-network
  bot-player-service:
    image: whattablackhole/fun_poker-bot-player-service-prod:latest
    container_name: bot-player-service-prod
    build:
      context: .
      dockerfile: ./bot-player-service/Dockerfile.prod
    environment:
      - GROQ_API=$GROQ_API
  load-balancer:
    image: whattablackhole/fun_poker-load-balancer-prod:latest
    container_name: load-balancer-prod
    ports:
      - 443:443
    build:
      context: .
      dockerfile: ./load-balancer/Dockerfile.prod
    volumes:
      - ${CERT_PATH}:/usr/local/openresty/certs/fullchain.pem
      - ${CERT_KEY_PATH}:/usr/local/openresty/certs/privkey.pem
      - ./public_key.pem:/etc/nginx/ssl/public_key.pem
    environment:
      - JWT_PUBLIC_KEY_FILE_PATH=/etc/nginx/ssl/public_key.pem
      - REDIS_HOST=game-cordinator-service-prod
      - REDIS_PORT=6379
    depends_on:
      - game-cordinator-service
      - frontend
    networks:
      - backend-network
      - frontend-network
      - auth-network
  frontend:
    image: whattablackhole/fun_poker-frontend-prod:latest
    container_name: frontend-prod
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    networks:
      - frontend-network
volumes:
  cargo-cache:
  pgdata1:
  pgdata2:
  target-cache:
  redis-data:
networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge
  auth-network:
    driver: bridge
