FROM rust:1.79.0 AS builder

WORKDIR /usr/src/game-service

COPY ./game-service /usr/src/game-service
COPY ./protos /usr/src/protos

RUN apt-get update && \
    apt-get install -y protobuf-compiler && \
    rm -rf /var/lib/apt/lists/*

RUN cargo build --release

FROM debian:bookworm-slim

COPY --from=builder /usr/src/game-service/target/release/fun_poker /usr/local/bin/app/fun_poker


WORKDIR /usr/local/bin/app

CMD ["./fun_poker"]

