// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "ai_bot_player.proto" (package "ai_bot_player", syntax proto3)
// tslint:disable
/**
 * @generated from protobuf enum ai_bot_player.BotModel
 */
export enum BotModel {
    /**
     * @generated from protobuf enum value: Llama3_70b_8192 = 0;
     */
    Llama3_70b_8192 = 0
}
