// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "client_request.proto" (package "client_request", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message client_request.JoinLobbyRequest
 */
export interface JoinLobbyRequest {
    /**
     * @generated from protobuf field: int32 lobby_id = 1;
     */
    lobbyId: number;
    /**
     * @generated from protobuf field: int32 player_id = 2;
     */
    playerId: number;
}
// @generated message type with reflection information, may provide speed optimized methods
class JoinLobbyRequest$Type extends MessageType<JoinLobbyRequest> {
    constructor() {
        super("client_request.JoinLobbyRequest", [
            { no: 1, name: "lobby_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "player_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<JoinLobbyRequest>): JoinLobbyRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.lobbyId = 0;
        message.playerId = 0;
        if (value !== undefined)
            reflectionMergePartial<JoinLobbyRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: JoinLobbyRequest): JoinLobbyRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 lobby_id */ 1:
                    message.lobbyId = reader.int32();
                    break;
                case /* int32 player_id */ 2:
                    message.playerId = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: JoinLobbyRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 lobby_id = 1; */
        if (message.lobbyId !== 0)
            writer.tag(1, WireType.Varint).int32(message.lobbyId);
        /* int32 player_id = 2; */
        if (message.playerId !== 0)
            writer.tag(2, WireType.Varint).int32(message.playerId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message client_request.JoinLobbyRequest
 */
export const JoinLobbyRequest = new JoinLobbyRequest$Type();
