// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "player.proto" (package "player", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { CardPair } from "./card";
import { Action } from "./game_state";
/**
 * @generated from protobuf message player.Player
 */
export interface Player {
    /**
     * @generated from protobuf field: string user_name = 1;
     */
    userName: string;
    /**
     * @generated from protobuf field: int32 user_id = 2;
     */
    userId: number;
    /**
     * @generated from protobuf field: string country = 3;
     */
    country: string;
    /**
     * @generated from protobuf field: optional game_state.Action action = 4;
     */
    action?: Action;
    /**
     * @generated from protobuf field: int32 bank = 5;
     */
    bank: number;
    /**
     * @generated from protobuf field: card.CardPair cards = 6;
     */
    cards?: CardPair;
    /**
     * @generated from protobuf field: int32 bet_in_current_seed = 7;
     */
    betInCurrentSeed: number;
    /**
     * @generated from protobuf field: player.PlayerStatus status = 8;
     */
    status: PlayerStatus;
    /**
     * @generated from protobuf field: bool is_bot = 9;
     */
    isBot: boolean;
}
/**
 * @generated from protobuf enum player.PlayerStatus
 */
export enum PlayerStatus {
    /**
     * @generated from protobuf enum value: WaitingForPlayers = 0;
     */
    WaitingForPlayers = 0,
    /**
     * @generated from protobuf enum value: SitOut = 1;
     */
    SitOut = 1,
    /**
     * @generated from protobuf enum value: Ready = 2;
     */
    Ready = 2,
    /**
     * @generated from protobuf enum value: Disconnected = 3;
     */
    Disconnected = 3,
    /**
     * @generated from protobuf enum value: Eliminated = 4;
     */
    Eliminated = 4
}
// @generated message type with reflection information, may provide speed optimized methods
class Player$Type extends MessageType<Player> {
    constructor() {
        super("player.Player", [
            { no: 1, name: "user_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "user_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "country", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "action", kind: "message", T: () => Action },
            { no: 5, name: "bank", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "cards", kind: "message", T: () => CardPair },
            { no: 7, name: "bet_in_current_seed", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 8, name: "status", kind: "enum", T: () => ["player.PlayerStatus", PlayerStatus] },
            { no: 9, name: "is_bot", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<Player>): Player {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.userName = "";
        message.userId = 0;
        message.country = "";
        message.bank = 0;
        message.betInCurrentSeed = 0;
        message.status = 0;
        message.isBot = false;
        if (value !== undefined)
            reflectionMergePartial<Player>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Player): Player {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string user_name */ 1:
                    message.userName = reader.string();
                    break;
                case /* int32 user_id */ 2:
                    message.userId = reader.int32();
                    break;
                case /* string country */ 3:
                    message.country = reader.string();
                    break;
                case /* optional game_state.Action action */ 4:
                    message.action = Action.internalBinaryRead(reader, reader.uint32(), options, message.action);
                    break;
                case /* int32 bank */ 5:
                    message.bank = reader.int32();
                    break;
                case /* card.CardPair cards */ 6:
                    message.cards = CardPair.internalBinaryRead(reader, reader.uint32(), options, message.cards);
                    break;
                case /* int32 bet_in_current_seed */ 7:
                    message.betInCurrentSeed = reader.int32();
                    break;
                case /* player.PlayerStatus status */ 8:
                    message.status = reader.int32();
                    break;
                case /* bool is_bot */ 9:
                    message.isBot = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Player, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string user_name = 1; */
        if (message.userName !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.userName);
        /* int32 user_id = 2; */
        if (message.userId !== 0)
            writer.tag(2, WireType.Varint).int32(message.userId);
        /* string country = 3; */
        if (message.country !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.country);
        /* optional game_state.Action action = 4; */
        if (message.action)
            Action.internalBinaryWrite(message.action, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* int32 bank = 5; */
        if (message.bank !== 0)
            writer.tag(5, WireType.Varint).int32(message.bank);
        /* card.CardPair cards = 6; */
        if (message.cards)
            CardPair.internalBinaryWrite(message.cards, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* int32 bet_in_current_seed = 7; */
        if (message.betInCurrentSeed !== 0)
            writer.tag(7, WireType.Varint).int32(message.betInCurrentSeed);
        /* player.PlayerStatus status = 8; */
        if (message.status !== 0)
            writer.tag(8, WireType.Varint).int32(message.status);
        /* bool is_bot = 9; */
        if (message.isBot !== false)
            writer.tag(9, WireType.Varint).bool(message.isBot);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message player.Player
 */
export const Player = new Player$Type();
