FROM mcr.microsoft.com/dotnet/sdk:8.0.203-alpine3.18-amd64 AS build

WORKDIR /app

COPY ./auth-service.csproj ./

RUN dotnet restore

COPY . .


RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0

WORKDIR /app

COPY --from=build /app/out .

# ENV ASPNETCORE_Kestrel__Certificates__Default__Password=
ENV ASPNETCORE_Kestrel__Certificates__Default__Path=/app/localhost.crt
ENV ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/app/localhost.key

ENTRYPOINT ["dotnet", "auth-service.dll", "--urls", "https://0.0.0.0:5004"]


EXPOSE 5004


