// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JoinLobbyRequest {
    #[prost(int32, tag = "1")]
    pub lobby_id: i32,
    #[prost(int32, tag = "2")]
    pub player_id: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StartGameRequest {
    #[prost(int32, tag = "1")]
    pub lobby_id: i32,
    #[prost(int32, tag = "2")]
    pub player_id: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ObserveLobbyRequest {
    #[prost(int32, tag = "2")]
    pub player_id: i32,
    #[prost(int32, tag = "1")]
    pub lobby_id: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateLobbyRequest {
    #[prost(message, optional, tag = "1")]
    pub payload: ::core::option::Option<super::lobby::Lobby>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SpawnBotRequest {
    #[prost(int32, tag = "1")]
    pub lobby_id: i32,
    #[prost(enumeration = "super::ai_bot_player::BotModel", tag = "2")]
    pub model: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlayerActionRequest {
    #[prost(int32, tag = "1")]
    pub player_id: i32,
    #[prost(int32, tag = "2")]
    pub lobby_id: i32,
    #[prost(message, optional, tag = "3")]
    pub action: ::core::option::Option<super::game_state::Action>,
}
