// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClientState {
    #[prost(int32, tag = "1")]
    pub player_id: i32,
    #[prost(message, optional, tag = "2")]
    pub cards: ::core::option::Option<super::card::CardPair>,
    #[prost(int32, tag = "3")]
    pub curr_player_id: i32,
    #[prost(int32, tag = "4")]
    pub curr_button_id: i32,
    #[prost(int32, tag = "5")]
    pub curr_small_blind_id: i32,
    #[prost(int32, tag = "6")]
    pub curr_big_blind_id: i32,
    #[prost(int32, tag = "7")]
    pub lobby_id: i32,
    #[prost(message, optional, tag = "8")]
    pub street: ::core::option::Option<super::game_state::Street>,
    #[prost(enumeration = "super::game_state::GameStatus", tag = "9")]
    pub game_status: i32,
    #[prost(message, repeated, tag = "10")]
    pub players: ::prost::alloc::vec::Vec<super::player::Player>,
    #[prost(message, optional, tag = "11")]
    pub showdown_outcome: ::core::option::Option<super::game_state::ShowdownOutcome>,
    #[prost(int32, tag = "12")]
    pub amount_to_call: i32,
    #[prost(int32, tag = "13")]
    pub min_amount_to_raise: i32,
    #[prost(bool, tag = "14")]
    pub can_raise: bool,
    #[prost(message, repeated, tag = "15")]
    pub action_history: ::prost::alloc::vec::Vec<super::player::Action>,
}
